use_frameworks!

target 'DLCMobilePlayer_Example' do
#  pod 'DLCMobilePlayer', :path => '../'
    pod 'DLCMobilePlayer', :git => 'https://github.com/dklinzh/DLCMobilePlayer.git'

  target 'DLCMobilePlayer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
